package com.newproduct.springboot.DTO;

import lombok.Data;
import org.springframework.web.multipart.MultipartFile;

@Data
public class UpdateDataDTO {
    private Integer id; //此id为当前更新的productid 用来查询并显示
    private MultipartFile fileUpdate1;
    private MultipartFile fileUpdate2;
    private MultipartFile fileUpdate3;
    private String factoryUpdate;
    private String skuUpdate;
    private String fbaUpdate;
    private String fbmUpdate;
    private String fulfillmentfeeamazonUpdate;
    private String fulfillmentfeeoutseaUpdate;
    private String productlenghcm1Update;
    private String productlenghcm2Update;
    private String productshortlenghcmUpdate;
    private String outboxlenghcm1Update;
    private String outboxlenghcm2Update;
    private String outboxshortlenghcmUpdate;
    private String weightkg1Update;
    private String weightkg2Update;
    private String productlenghinch1Update;
    private String productlenghinch2Update;
    private String productshortlenghinchUpdate;
    private String outboxlenghinch1Update;
    private String outboxlenghinch2Update;
    private String outboxshortlenghinchUpdate;
    private String weightlb1Update;
    private String weightlb2Update;
    private String quantityhqUpdate;
    private String quantityUpdate;
    private String inboxlenghinch1Update;
    private String inboxlenghinch2Update;
    private String inboxshortlenghinchUpdate;
    private String inboxweightlb1Update;
    private String inboxweightlb2Update;
    private String inboxlenghcm1Update;
    private String inboxlenghcm2Update;
    private String inboxshortlenghcmUpdate;
    private String inboxweightkg1Update;
    private String inboxweightkg2Update;
    private String minlenghinchheightUpdate;
    private String minlenghinchwidthUpdate;
    private String minlenghinchhighUpdate;
    private String minweight1Update;
    private String minweight2Update;
    private String typeUpdate;


    private String factory; //工厂
    private String sku;
    private String fba;
    private String fbm;
    private String fulfillmentfeeamazon;
    private String fulfillmentfeeoutsea;
    private String productlenghcm1;
    private String productlenghcm2;
    private String productshortlenghcm;
    private String outboxlenghcm1;
    private String outboxlenghcm2;
    private String outboxshortlenghcm;
    private String weightkg1;
    private String weightkg2;
    private String productlenghinch1;
    private String productlenghinch2;
    private String productshortlenghinch;
    private String outboxlenghinch1;
    private String outboxlenghinch2;
    private String outboxshortlenghinch;
    private String weightlb1;
    private String weightlb2;
    private String quantityhq;
    private String quantity;
    private String inboxlenghinch1;
    private String inboxlenghinch2;
    private String inboxshortlenghinch;
    private String inboxweightlb1;
    private String inboxweightlb2;
    private String inboxlenghcm1;
    private String inboxlenghcm2;
    private String inboxshortlenghcm;
    private String inboxweightkg1;
    private String inboxweightkg2;
    private String minlenghinchheight;
    private String minlenghinchwidth;
    private String minlenghinchhigh;
    private String minweight1;
    private String minweight2;
    private String type; //产品类型

//    private String currentFactoryUpdate;
//    private String currentSkuUpdate;
//    private String currentFbaUpdate;
//    private String currentFbmUpdate;
//    private String currentFulfillmentfeeamazonUpdate;
//    private String currentFulfillmentfeeoutseaUpdate;
//    private String currentProductlenghcm1Update;
//    private String currentProductlenghcm2Update;
//    private String currentProductshortlenghcmUpdate;
//    private String currentOutboxlenghcm1Update;
//    private String currentOutboxlenghcm2Update;
//    private String currentOutboxshortlenghcmUpdate;
//    private String currentWeightkg1Update;
//    private String currentWeightkg2Update;
//    private String currentProductlenghinch1Update;
//    private String currentProductlenghinch2Update;
//    private String currentProductshortlenghinchUpdate;
//    private String currentOutboxlenghinch1Update;
//    private String currentOutboxlenghinch2Update;
//    private String currentOutboxshortlenghinchUpdate;
//    private String currentWeightlb1Update;
//    private String currentWeightlb2Update;
//    private String currentQuantityhqUpdate;
//    private String currentQuantityUpdate;
//    private String currentInboxlenghinch1Update;
//    private String currentInboxlenghinch2Update;
//    private String currentInboxshortlenghinchUpdate;
//    private String currentInboxweightlb1Update;
//    private String currentInboxweightlb2Update;
//    private String currentInboxlenghcm1Update;
//    private String currentInboxlenghcm2Update;
//    private String currentInboxshortlenghcmUpdate;
//    private String currentInboxweightkg1Update;
//    private String currentInboxweightkg2Update;
//    private String currentMinlenghinchheightUpdate;
//    private String currentMinlenghinchwidthUpdate;
//    private String currentMinlenghinchhighUpdate;
//    private String currentMinweight1Update;
//    private String currentMinweight2Update;
//    private String currentTypeUpdate;
}
